version: "3"

x-bitcoind: &default-bitcoind
  container_name: bitcoind
  image: ruimarinho/bitcoin-core:0.20-alpine
  env_file: .env
  command: [
    "-chain=${BTCD_NETWORK}",
    "-datadir=/bitcoin/.bitcoin",
    "-rpcuser=${BTCD_RPCUSER}",
    "-rpcpassword=${BTCD_RPCPASS}",
    "-rpcport=${BTCD_RPCPORT}",
    "-rpcbind=0.0.0.0:${BTCD_RPCPORT}",
    "-rpcallowip=0.0.0.0/0",
    "-listenonion=0",
    "-fallbackfee=0.000001",  # 100 sats
    "-printtoconsole",
    "-server",
    "-txindex",
    # "-addnode=bitcoind-house",
    # "-addnode=bitcoind-alice",
    # "-addnode=bitcoind-bob",
    "-zmqpubrawblock=tcp://0.0.0.0:28332",
    "-zmqpubrawtx=tcp://0.0.0.0:28333"
  ]

services:
  bitcoind:
    <<: *default-bitcoind
    container_name: bitcoind
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin

  ali-lnd: &lnd
    container_name: ali-lnd
    hostname: ali-lnd
    build:
      context: .
      dockerfile: dockerfile/lnd/Dockerfile
    image: lnd
    depends_on:
      - bitcoind
    env_file: .env
    command: [
      "--noseedbackup",
      "--bitcoin.active",
      "--bitcoin.node=bitcoind",
      "--bitcoin.${BTCD_NETWORK}",
      "--bitcoind.rpchost=bitcoind",
      "--bitcoind.rpcuser=${BTCD_RPCUSER}",
      "--bitcoind.rpcpass=${BTCD_RPCPASS}",
      "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332",
      "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333",
      "--rpclisten=$HOSTNAME:10009",
      "--rpclisten=localhost:10009",
      "--debuglevel=info"
    ]

  bob-lnd:
    <<: *lnd
    container_name: bob-lnd
    hostname: bob-lnd

  jupyter:
    container_name: jupyter
    hostname: jupyter
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    image: jupyter
    env_file: .env
    volumes:
      - ./:/notebooks
    ports:
      - 8888:8888
    depends_on:
      - bitcoind

volumes:
  bitcoind:
