version: '2'
services:
    btcd:
      image: btcd
      container_name: btcd
      build:
        context: btcd/
      volumes:
        - shared:/rpc
        - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
        - MINING_ADDRESS
      ports:
        - 18556:18556
      entrypoint: ["./start-btcd.sh"]

    btcwallet:
      image: btcwallet
      container_name: btcwallet
      build:
        context: btcwallet/
        dockerfile: wallet.Dockerfile
      volumes:
        - shared:/rpc
        - wallet:/root/.btcwallet
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
      ports:
        - 18554:18554
      entrypoint: ["./start-btcwallet.sh"]
      links:
        - "btcd:blockchain"

    lnd:
      image: lnd
      container_name: lnd
      build:
        context: lnd/
        dockerfile: dev.Dockerfile
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
        - shared:/rpc
        - lnd:/root/.lnd
      entrypoint: ["./start-lnd.sh"]
      links:
        - "btcd:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcd and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # wallet volume is needed for maintaining wallet persistence
  # during btcwallet container recreation.
  wallet:
    driver: local

  # lnd volume is used for persisting lnd application data and chain state
  # during container lifecycle.
  lnd:
    driver: local
